apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-pvc
  namespace: adguard-home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home-deployment
  namespace: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: webui
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: adguardhome-data
              mountPath: /opt/adguardhome/work
            - name: adguardhome-conf
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: adguardhome-data
          persistentVolumeClaim:      
            claimName: adguardhome-pvc
        - name: adguardhome-conf
          persistentVolumeClaim:      
            claimName: adguardhome-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-svc
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: adguard-home
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: webui
      port: 3000 
      targetPort: 3000
      protocol: TCP
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: adguard-ui-ingress
#   namespace: adguard-home
#   annotations:
#     cert-manager.io/cluster-issuer: internal-cluster-issuer
# spec:
#   ingressClassName: tailscale
#   tls:
#     - hosts:
#       - adguard.cobia-mountain.ts.net
#       secretName: adguard-tls
#   rules:
#   - host: adguard.cobia-mountain.ts.net
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: adguard-home-service
#             port:
#               number: 3000  # Back to 3000 for web UI