apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-pvc
  namespace: adguard-home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home-deployment
  namespace: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome
          ports:
            - containerPort: 3000     # Web UI port
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 853
              protocol: TCP
          volumeMounts:
            - name: adguardhome-data
              mountPath: /opt/adguardhome/work
              subPath: work           # Added subPath to separate work and conf
            - name: adguardhome-data
              mountPath: /opt/adguardhome/conf
              subPath: conf           # Added subPath to separate work and conf
      volumes:
        - name: adguardhome-data
          persistentVolumeClaim:      # Uncommented to use persistent storage
            claimName: adguardhome-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-service
  namespace: adguard-home
spec:
  type: ClusterIP
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: web-ui
      port: 3000            # Back to 3000 for web UI
      targetPort: 3000      # Back to 3000 for web UI
      protocol: TCP
    - name: dns-over-tls
      port: 853
      targetPort: 853
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-service
  namespace: adguard-home
spec:
  type: NodePort            # NodePort for external DNS access
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30053       # External port for DNS queries
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30053       # External port for DNS queries
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ui-ingress
  namespace: adguard-home
  annotations:
    cert-manager.io/cluster-issuer: internal-cluster-issuer
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - adguard.cobia-mountain.ts.net
      secretName: adguard-tls
  rules:
  - host: adguard.cobia-mountain.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adguard-home-service
            port:
              number: 3000  # Back to 3000 for web UI