apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home-tailscale-auth
  namespace: adguard-home
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: adguard-home-tailscale-auth
  data:
    - secretKey: adguard-home-tailscale-auth-secret
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: adguard-home-tailscale-auth-secret
        metadataPolicy: None
   