nameOverride: "traefik-private"

global:
  checkNewVersion: true
  sendAnonymousUsage: true
image:  
  registry: ghcr.io/traefik
  repository: traefik
  pullPolicy: IfNotPresent
  
ingressClass:
  enabled: true
  name: "traefik-private"
  isDefaultClass: false

priorityClassName: "system-cluster-critical"

service:
  type: LoadBalancer
  annotations:
    tailscale.com/expose: "true"

  
providers:
  kubernetesCRD:
    ingressClass: "traefik-private"
  kubernetesIngress:
    ingressClass: "traefik-private"
