global:
  checkNewVersion: true
  sendAnonymousUsage: true
deployment:
  image:
    registry: ghcr.io/traefik
    name: traefik
    tag: "v2.11"
ingressClass:
  enabled: true
  name: traefik-private
  isDefaultClass: false

providers:
  kubernetesCRD:
    ingressClass: traefik-private
  kubernetesIngress:
    ingressClass: traefik-private

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web

entryPoints:
  web:
    address: ":8000"
