nameOverride: "traefik-private"

global:
  checkNewVersion: true
  sendAnonymousUsage: true
image:  
  registry: ghcr.io/traefik
  repository: traefik
  pullPolicy: IfNotPresent
  
ingressClass:
  enabled: true
  name: "traefik-private"
  isDefaultClass: false

priorityClassName: "system-cluster-critical"

providers:
  kubernetesCRD:
    ingressClass: "traefik-private"
    namespaces: []
  kubernetesIngress:
    ingressClass: "traefik-private"
    namespaces: []
