global:
  checkNewVersion: true
  sendAnonymousUsage: true
image:  
  registry: ghcr.io/traefik
  repository: traefik
  pullPolicy: IfNotPresent
  
ingressClass:
  enabled: true
  name: traefik-private
  isDefaultClass: false

providers:
  kubernetesIngress:
    ingressClass: traefik-private

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web

entryPoints:
  web:
    address: ":8000"
