apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab
servers: 1
ports:

  - port: 31443-31444:31443-31444
    nodeFilters:
      - loadbalancer

  - port: 30081-30083:30081-30083
    nodeFilters:
      - loadbalancer

  # default HTTP port:
  - port: 80:80
    nodeFilters:
      - loadbalancer

  # default HTTPS port:
  - port: 443:443
    nodeFilters:
      - loadbalancer

  # *** ADD THESE LINES FOR PI-HOLE DNS ***
  - port: 53:53/udp
    nodeFilters:
      - loadbalancer
      
  - port: 53:53/tcp
    nodeFilters:
      - loadbalancer
