# homelab-argo/manifests/certs/cloudflare-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: letsencrypt-staging-cloudflare
spec:
  acme:
    email: choozexian@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cloudflare:
          email: choozexian@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret 
            key: api-token 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd # ArgoCD services are in the 'argocd' namespace
spec:
  entryPoints:
    - websecure # Assumes Traefik's websecure (HTTPS) entrypoint
  routes:
    - match: Host(`argo.seanchoo.top`)
      kind: Rule
      services:
        - name: argocd-server # The name of ArgoCD's UI service
          port: 443 # The HTTPS port of the argocd-server service
  tls:
    secretName: argocd-cert-secret # Name of the Kubernetes Secret that will hold your TLS certificate
                                   # This secret needs to be created by cert-manager or manually
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-server-cert
  namespace: argocd 
spec:
  secretName: argocd-secret-tls
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
  commonName: argo.seanchoo.top
  dnsNames:
    - argo.seanchoo.top
