apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: kube-prometheus-stack
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
  data:
    - secretKey: admin-user
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: grafana-admin
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: grafana-admin-password 
