grafana:
  ingress:
    enabled: true
    ingressClassName: traefik 
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    hosts:
      - grafana.seanchoo.top
    paths:
      - /
  defaultDashboardsTimezone: PDT
  persistence:
    enabled: true
    type: sts
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    finalizers:
      - kubernetes.io/pvc-protection
    tls: 
      - secretName: grafana-general-tls
        hosts:
        - grafana.seanchoo.top
prometheus:
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    hosts: 
      - prometheus.seanchoo.top
    paths: 
      - /
    tls: 
      - secretName: prometheus-general-tls
        hosts:
        - prometheus.seanchoo.top