grafana:
  adminPassword: ""
  admin:
    user: admin
    existingSecret: grafana-admin-secret 
    passwordKey: GF_SECURITY_ADMIN_PASSWORD

  ingress:
    enabled: true
    ingressClassName: traefik 
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    hosts:
      - grafana.seanchoo.top
    paths:
      - /
    tls: 
      - secretName: grafana-general-tls
        hosts:
        - grafana.seanchoo.top
  defaultDashboardsTimezone: PDT
  persistence:
    # enabled: true
    enabled: false
    type: sts
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    finalizers:
      - kubernetes.io/pvc-protection
    
  env:
    GF_SERVER_ROOT_URL: https://grafana.seanchoo.top
    
prometheus:
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    hosts: 
      - prometheus.seanchoo.top
    paths: 
      - /
    tls: 
      - secretName: prometheus-general-tls
        hosts:
        - prometheus.seanchoo.top