apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/authentik
      ref: values
    
    - repoURL: https://charts.goauthentik.io/
      chart: goauthentik
      targetRevision: 0.10.0
      helm:
        valueFiles:
          - $values/manifests/authentik/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
