apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  labels:
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/couchdb
      ref: values
    
    - repoURL: https://apache.github.io/couchdb-helm
      chart: couchdb
      targetRevision: 4.6.1
      helm:
        valueFiles:
          - $values/manifests/couchdb/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: couchdb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

