apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: default
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: authentik-secret
  data:
    - secretKey: postgres-password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: authentik-postgres-password
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: authentik-postgres-password
    - secretKey: authentik-postgres-password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: authentik-postgres-password
        metadataPolicy: None
    - secretKey: authentik-secret-key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: authentik-secret-key
        metadataPolicy: None
    - secretKey: authentik-redis-password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: authentik-redis-password
        metadataPolicy: None
