authentik:
  secret_key: "PleaseGenerateA50CharKey"
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  # service:
  #   annotations:
  #     traefik.ingress.kubernetes.io/router.entrypoints: websecure 
  #     cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare

  ingress:
    enabled: true
    hosts:
        - authentik.seanchoo.top
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    ingressClassName: traefik

# prometheus:
#   rules:
#     enabled: true

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"

redis:
  enabled: true