worker:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: password
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: secret_key
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-redis-password

server:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-postgres-password
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-redis-password
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-secret-key
  ingress:
    enabled: true
    hosts:
      - authentik.seanchoo.top
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    tls:
      - secretName: authentik-tls-secret
        hosts:
          - authentik.seanchoo.top

# prometheus:
#   rules:
    # enabled: true

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-secret
    secretKeys:
      userPasswordKey: authentik-postgres-password
      adminPasswordKey: authentik-postgres-password
      replicationPasswordKey: authentik-postgres-password
    usePasswordFiles: false

  primary:
    persistence:
      enable: true
      size: 500Mi
  readReplicas:
    persistence:
      enable: true
      size: 500Mi
   
redis:
  enabled: true
  master:
    persistence:
      size: 500Mi
