authentik:
  secret_key: "PleaseGenerateA50CharKey"
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  service:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare

  ingress:
    enabled: true
    hosts:
        - authentik.seanchoo.top
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    tls:
      - secretName: authentik-tls-secret
        hosts:
          - authentik.seanchoo.top
# prometheus:
#   rules:
#     enabled: true

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"

redis:
  enabled: true

primary:
  persistence:
    enable: true
    size: 500Mi

readReplicas:
  persistence:
    enable: true
    size: 500Mi
