global:
  addPrometheusAnnotations: true
  
authentik:
  secret_key: 
    valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-secret-key
  postgresql:
    password: 
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-postgres-password
  redis:
    password:
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: authentik-redis-password

server:
  ingress:
    enabled: true
    hosts:
      - authentik.seanchoo.top
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    tls:
      - secretName: authentik-tls-secret
        hosts:
          - authentik.seanchoo.top

# prometheus:
#   rules:
    # enabled: true

postgresql:
  enabled: true
  auth:
    password:
      valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: authentik-postgres-password
  primary:
    persistence:
      enable: true
      size: 500Mi
  readReplicas:
    persistence:
      enable: true
      size: 500Mi
   
redis:
  enabled: true
  master:
    persistence:
      size: 500Mi
