apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  labels:
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/tailscale
      ref: values
    
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.84.3
      helm:
        valueFiles:
          - $values/manifests/tailscale/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
