image:
  repository: ghcr.io/techno-tim/littlelink-server
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: America/Los_Angeles
  META_TITLE: Sean Choo
  META_DESCRIPTION: Sean Choo Link page
  META_AUTHOR: Sean Choo
  THEME: Dark
  FAVICON_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_2X_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
  AVATAR_ALT: Sean Choo Profile Pic
  NAME: Sean Choo
  BIO: Hey! Just a place where you can connect with me!
  GITHUB: https://github.com/zexianchoo
  # TWITTER: https://twitter.com/TechnoTimLive
  # INSTAGRAM: https://www.instagram.com/techno.tim
  # YOUTUBE: https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
  # TWITCH: https://www.twitch.tv/technotim/
  # DISCORD: https://discord.gg/DJKexrJ
  # TIKTOK: https://www.tiktok.com/@technotim
  # KIT: https://kit.co/TechnoTim
  # FACEBOOK: https://facebook.com
  # FACEBOOK_MESSENGER: https://facebook.com
  # LINKED_IN: https://linkedin.com
  # PRODUCT_HUNT: https://www.producthunt.com/
  # SNAPCHAT: https://www.snapchat.com/
  # SPOTIFY: https://www.spotify.com/
  # REDDIT: https://www.reddit.com/
  # MEDIUM: https://medium.com
  # PINTEREST: https://www.pinterest.com/
  # EMAIL: you@example.com
  # EMAIL_ALT: you@example.com
  # SOUND_CLOUD: https://souncloud.com
  # FIGMA: https://figma.com
  # TELEGRAM: https://telegram.org/
  # TUMBLR: https://www.tumblr.com/
  # STEAM: https://steamcommunity.com/
  # VIMEO: https://vimeo.com/
  # WORDPRESS: https://wordpress.com/
  # GOODREADS: https://www.goodreads.com/
  # SKOOB: https://www.skoob.com.br/
  FOOTER: Thanks for stopping by!

service:
  main:
    ports:
      http:
        port: 3000
        
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  ingressClassName: traefik
  hosts:
    - host: links.seanchoo.top
      paths:
      - path: /
        pathType: Prefix
  tls:
    - secretName: littlelink-tls
    - hosts:
      - links.seanchoo.top

persistence:
  config:
    enabled: true
    mountPath: /config
    storageClassName: local-path
    accessMode: ReadWriteOnce
    size: 200Mi
