apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This is the name of the Application in Argo CD
  name: nginx
  # This Application resource itself must live in the 'argocd' namespace
  namespace: argocd
  finalizers:
    # This ensures that when you delete the Application in Argo CD,
    # it also deletes all the resources it created (the Deployment and Service).
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # This source block is the key.
  # It tells Argo CD to look for plain Kubernetes manifests.
  source:
    # It points to your Git repository...
    repoURL: https://github.com/zexianchoo/homelab-argo.git #<-- Your Git repo
    targetRevision: HEAD
    # ...and specifically to the path where the manifests are located.
    # In this case, it's the same directory this file is in.
    path: apps/nginx

  destination:
    server: 'https://kubernetes.default.svc'
    # The Kubernetes namespace where the NGINX pods will be created.
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true