apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/zexianchoo/homelab-argo.git
    targetRevision: HEAD
    path: manifests/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 