apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: tailscale-secret
  data:
    - secretKey: tailscale-oauth-clientid
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: tailscale-oauth-clientid
        metadataPolicy: None
    - secretKey: tailscale-oauth-client-password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: tailscale-oauth-client-password
        metadataPolicy: None
