apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: tailscale-oauth-clientid
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: tailscale-oauth-client-password
        metadataPolicy: None
