apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config-claim
  namespace: homer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi 
  storageClassName: local-path