apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config-claim
  namespace: homer
finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi 
  storageClassName: local-path