apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ts-ingress
  namespace: jellyfin
spec:
  ingressClassName: tailscale
  rules:
    - host: jellyfin.hydra-cliff.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jellyfin-svc-ts
#   namespace: jellyfin 
# spec:
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 8096        
#       targetPort: 8096
#   selector:
#     app.kubernetes.io/name: jellyfin
#     app.kubernetes.io/instance: jellyfin
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: jellyfin-svc-ts
#   namespace: jellyfin
# subsets:
#   - addresses:
#       - ip: "172.21.0.1" 
#     ports:
#       - port: 8096