ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
  tls:
    - hosts:
      - jellyfin.seanchoo.top
      secretName: jellyfin-tls
  hosts:
    - host: jellyfin.seanchoo.top
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jellyfin
              port:
                number: 8096
service:
   type: NodePort

persistence:
  config:
    enabled: true
    size: 5Gi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: local-path
