ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: jellyfin.hydra-cliff.ts.net
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    size: 5Gi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: local-path
