ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: jellyfin.hydra-cliff.ts.net
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jellyfin
              port:
                number: 8096

persistence:
  config:
    enabled: false
    size: 5Gi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: local-path
