apiVersion: v1
kind: Service
metadata:
  name: immich-server-external 
  namespace: immich 
spec:
  ports:
    - protocol: TCP
      port: 2283        
      targetPort: 2283
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: immich-server-external
#   namespace: immich
# subsets:
#   - addresses:
#       - ip: "172.21.0.1" 
#     ports:
#       - port: 2283
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: immich-ingressroute
#   namespace: immich 
# spec:
#   entryPoints:
#     - web
#     - websecure 
#   routes:
#     - match: Host(`immich.seanchoo.top`)
#       kind: Rule
#       services:
#         - name: immich-server-external 
#           port: 2283 
#           scheme: http
#   tls:
#     # certResolver: letsencrypt-prod-cloudflare
#     secretName: immich-tls
#     # hosts:
#     #   - immich.seanchoo.top 

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: immich-tls # Give it a distinct name
#   namespace: immich          # Ensure this is the same namespace as your IngressRoute
# spec:
#   secretName: immich-tls     # This MUST match the secretName in your IngressRoute
#   issuerRef:  
#     name: letsencrypt-prod-cloudflare # This MUST match your ClusterIssuer name
#     kind: ClusterIssuer
#   dnsNames:
#     - immich.seanchoo.top 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
  # Annotations are used to configure behavior
  annotations:
    # 1. Tell cert-manager which ClusterIssuer to use for this Ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    # 2. Tell Traefik this is for the websecure (HTTPS) entrypoint
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # 3. Tell Traefik to handle TLS
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  # 4. Define the TLS certificate details
  tls:
  - hosts:
    - immich.seanchoo.top
    # cert-manager will create and manage this secret for you
    secretName: immich-tls
  # 5. Define the routing rules
  rules:
  - host: immich.seanchoo.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          # 6. Point to the same service you created earlier
          service:
            name: immich-server-external
            port:
              number: 2283