apiVersion: v1
kind: Service
metadata:
  name: immich-server-external 
  namespace: default 
spec:
  ports:
    - protocol: TCP
      port: 2283        
      targetPort: 2283
---
apiVersion: v1
kind: Endpoints
metadata:
  name: immich-server-external
  namespace: default
subsets:
  - addresses:
      - ip: "172.21.0.1" 
    ports:
      - port: 2283
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingressroute
  namespace: default 
spec:
  entryPoints:
    - web
    - websecure 
  routes:
    - match: Host(`immich.seanchoo.top`)
      kind: Rule
      services:
        - name: immich-server-external 
          port: 2283 
  tls:
    certResolver: letsencrypt-prod-cloudflare
    secretName: immich-tls

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tls-certificate # Give it a distinct name
  namespace: default          # Ensure this is the same namespace as your IngressRoute
spec:
  secretName: immich-tls     # This MUST match the secretName in your IngressRoute
  issuerRef:
    name: letsencrypt-prod-cloudflare # This MUST match your ClusterIssuer name
    kind: ClusterIssuer
  dnsNames:
    - immich.seanchoo.top