apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-claim 
  namespace: immich
finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 
  storageClassName: local-path