apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-claim 
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  storageClassName: local-path