apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - immich.seanchoo.top
    secretName: immich-tls
  rules:
  - host: immich.seanchoo.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-server-external
            port:
              number: 2283
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ts-ingress
  namespace: immich
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - immich.hydra-cliff.ts.net
  rules:
    - host: immich.hydra-cliff.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server-external
                port:
                  number: 2283
