apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ts-ingress
  namespace: immich
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - immich.hydra-cliff.ts.net
  rules:
    - host: immich.hydra-cliff.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server-external
                port:
                  number: 2283
