serviceAccount:
  create: true

env:
  - name: TZ
    value: US/PDT
  - name: PASSWD
    valueFrom:
      secretKeyRef:
        name: secret-name
        key: key-name
hostname: immich.seanchoo.top

service:
  main:
    ports:
      http:
        primary: false
      https:
        enabled: true
        primary: true
        protocol: HTTPS

serviceMonitor:
  enabled: true

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    ingressClassName: traefik
    hosts:
      host: immich.seanchoo.top

persistence:
  config:
    enabled: true
    size: 200Mi
