global:
  checkNewVersion: true
  sendAnonymousUsage: true
image:  
  registry: ghcr.io/traefik
  repository: traefik
  pullPolicy: IfNotPresent
priorityClassName: "system-cluster-critical"

ingressClass:
  name: "traefik"
  enabled: true
  isDefaultClass: false
