admin:
  user: admin
  existingSecret: grafana-admin-secret 
  passwordKey: GF_SECURITY_ADMIN_PASSWORD
  
env:
  GF_SERVER_ROOT_URL: https://grafana.seanchoo.top
    
# Service configuration
service:
  type: ClusterIP 
  port: 80  

ingress:
  enabled: true
  ingressClassName: traefik 
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure 
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare

  hosts:
    - grafana.seanchoo.top

  tls:
    - secretName: grafana-tls-secret 
      hosts:
        - grafana.seanchoo.top 

persistence:
  type: pvc
  enabled: true
  size: 200Mi
  finalizers:
    - kubernetes.io/pvc-protection