# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: traefik-private
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: https://github.com/zexianchoo/homelab-argo.git
#       targetRevision: HEAD
#       path: manifests/traefik-private
#       ref: values
    
#     - repoURL: https://traefik.github.io/charts
#       chart: traefik
#       targetRevision: 36.3.0
#       helm:
#         valueFiles:
#           - $values/manifests/traefik-private/values.yaml
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: default

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
