apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-root
  namespace: argocd
spec:
  project: default
  generators:
  - git: 
      repoURL: https://github.com/zexianchoo/homelab-argo.git
      revision: HEAD
      files:
      - path: apps/*/*.yaml

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/zexianchoo/homelab-argo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true