apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/zexianchoo/homelab-argo.git
    targetRevision: HEAD
    path: apps 
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault 
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: https://homelab-key-vault.vault.azure.net/
      tenantId: af8036c0-68ca-4751-bb29-7d6db996bdd1
      authSecretRef:
        clientId:
          name: azure-key-vault-credentials
          key: client_id
          namespace: external-secrets         
        clientSecret:
          name: azure-key-vault-credentials
          key: client_secret
          namespace: external-secrets       
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-api-token
        # refreshInterval: "1d"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd-admin-password
        # refreshInterval: "1d"
    - secretKey: server.secretkey
      remoteRef:
        key: argocd-secret-key
        # refreshInterval: "1d"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-gh-credentials
  namespace: argocd
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: argo-gh-credentials
    template:
      stringData:
        repoUrl: https://github.com/zexianchoo/homelab-argo.git
        username: zexianchoo
  data:
    - secretKey: password
      remoteRef:
        key: github-pat
        # refreshInterval: "1d"