# homelab-argo/manifests/certs/cloudflare-clusterissuer.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: choozexian@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: choozexian@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret 
            key: api-token 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd 
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`argo.seanchoo.top`)
      kind: Rule
      services:
        - name: argocd-server 
          port: 443 
  tls:
    secretName: argocd-server-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-cluster-issuer
spec:
  ca:
    secretName: internal-tls-key-pair
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-tls-key-pair
  namespace: cert-manager
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: internal-tls-key-pair
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: internal-tls-cert
        metadataPolicy: None
    - secretKey: tls.key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: internal-tls-key
        metadataPolicy: None
