# homelab-argo/manifests/certs/cloudflare-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # Use ClusterIssuer for cluster-wide certificates
metadata:
  name: cloudflare-prod-issuer
spec:
  acme:
    # You MUST replace this with your email address!
    email: your-email@example.com
    server: https://acme-v02.api.letsencrypt.org/directory # Let's Encrypt production ACME server
    privateKeySecretRef:
      # Secret for ACME account private key (cert-manager manages this)
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: your-email@example.com # Email used for Cloudflare API token setup
          apiTokenSecretRef:
            name: cloudflare-api-token-secret # Reference the secret created above
            key: api-token # Key within the secret that holds the API token
      selector: {} # Leave empty to use for all domains, or specify a selector if needed

      
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd # ArgoCD services are in the 'argocd' namespace
spec:
  entryPoints:
    - websecure # Assumes Traefik's websecure (HTTPS) entrypoint
  routes:
    - match: Host(`argo.seanchoo.top`)
      kind: Rule
      services:
        - name: argocd-server # The name of ArgoCD's UI service
          port: 443 # The HTTPS port of the argocd-server service
  tls:
    secretName: argocd-cert-secret # Name of the Kubernetes Secret that will hold your TLS certificate
                                   # This secret needs to be created by cert-manager or manually
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-seanchoo-top-cert
  namespace: argocd # Or whatever namespace your ArgoCD IngressRoute is in
spec:
  secretName: argocd-cert-secret # This must match the secretName in your IngressRoute
  dnsNames:
    - argo.seanchoo.top
  issuerRef:
    name: cloudflare-prod-issuer # <--- Reference your new ClusterIssuer
    kind: ClusterIssuer
    group: cert-manager.io
---
