# homelab-argo/manifests/certs/cloudflare-clusterissuer.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: choozexian@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: choozexian@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret 
            key: api-token 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd 
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`argo.seanchoo.top`)
      kind: Rule
      services:
        - name: argocd-server 
          port: 443 
  tls:
    secretName: argocd-server-tls