nameOverride: argocd

dex:
  enabled: false

server:
  service:
    type: NodePort 
    nodePortHttp: 30080
    nodePortHttps: 31443
  ingress:
    enabled: false
    hosts:
      - host: argocd.seanchoo.top
    tls: true

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$5vm8wXaSdbuff0m9l21JdevzXBzJFPCi8sy6OOnpZMAG.fOXL7jvO" #admin

