global:
  domain: argo.seanchoo.top

dex:
  enabled: false

server:
  service:
    type: NodePort 
    nodePortHttp: 30080
    nodePortHttps: 31443
  ingress:
    enabled: false
    hosts:
      - host: argocd.seanchoo.top
    tls: true
