global:
  domain: argo.seanchoo.top

dex:
  enabled: false

server:
  service:
    type: NodePort 
    nodePortHttp: 30080
    nodePortHttps: 31443
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argo.seanchoo.top
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
      traefik.ingress.kubernetes.io/router.scheme: https
    extraHosts: 
      - name: argofixed.seanchoo.top
        path: /

    tls: true

