apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: internal-cluster-issuer
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - argocd.cobia-mountain.ts.net
      secretName: argocd-ingress-tls 
  rules:
  - host: argocd.cobia-mountain.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 31443
---
