# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-ingress
#   namespace: argocd
#   annotations:
#     cert-manager.io/cluster-issuer: internal-cluster-issuer
# spec:
#   ingressClassName: tailscale
#   tls:
#     - hosts:
#       - argo.cobia-mountain.ts.net
#       secretName: argocd-ingress-tls 
#   rules:
#   - host: argo.cobia-mountain.ts.net
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argo-cd-argocd-server
#             port:
#               number: 80
