ingress:
  enabled: true
  className: tailscale
  annotations: 
    cert-manager.io/cluster-issuer: internal-cluster-issuer
  hosts:
    - host: jellyfin.cobia-mountain.ts.net
      paths:
        - path: /
          pathType: Prefix
  tls: 
  - hosts:
    - jellyfin
  #   secretName: jellyfin-private-tls
  # rules:
  # - host: jellyfin.cobia-mountain.ts.net
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: jellyfin-private
  #           port:
  #             number: 8096

persistence:
  config:
    enabled: true
    size: 5Gi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: local-path
