ingress:
  enabled: false
  className: tailscale
  hosts:
    - host: jellyfin2.hydra-cliff.ts.net
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts:
      - jellyfin2.hydra-cliff.ts.net
      secretName: jellyfin-private-tls
  rules:
    - host: jellyfin2.hydra-cliff.ts.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jellyfin-private
              port:
                number: 8096

service:
  type: LoadBalancer
  loadBalancerClass: tailscale
  
persistence:
  config:
    enabled: true
    size: 5Gi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: local-path
