apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: homelab-root
  name: ingress-appset
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: ingress/*.yaml
        repoURL: https://github.com/zexianchoo/homelab-argo.git
        revision: HEAD
  template:
    metadata:
      name: '{{hostname}}-ingress'
      namespace: '{{namespace}}'
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/zexianchoo/homelab-argo.git 
        targetRevision: HEAD                                      # <-- FIX 2: Add the revision here

        # The rest of your configuration is correct
        chart: . # This placeholder is fine in this context
        helm:
          parameters:
            - name: hostname
              value: '{{hostname}}'
            - name: serviceName
              value: '{{serviceName}}'
            - name: servicePort
              value: '{{servicePort}}'
            - name: scheme
              value: '{{scheme}}'
          releaseName: ingresstemplate
          values: |
            manifest: |
              apiVersion: traefik.containo.us/v1alpha1
              kind: IngressRoute
              metadata:
                name: '{{ .Values.serviceName }}'
              spec:
                entryPoints:
                  - websecure
                routes:
                  - match: Host(`{{ .Values.hostname }}`)
                    kind: Rule
                    services:
                      - name: '{{ .Values.serviceName }}'
                        port: {{ .Values.servicePort }}
                        {{- if .Values.scheme }}
                        scheme: {{ .Values.scheme }}
                        {{- end }}
                tls:
                  certResolver: myresolver
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true