apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zexianchoo/homelab-argo.git
      revision: HEAD
      # Scan for all the ingress definition YAML files
      files:
      - path: "ingress/*.yaml"

  template:
    metadata:
      # Use the filename for the app name (e.g., "argocd-ingress")
      name: '{{path.basenameNormalized}}-ingress'
      namespace: '{{namespace}}' # Use namespace from params file
    spec:
      project: "default"
      # We are not using Helm here. We are generating a manifest directly.
      source:
        # This is a clever trick to define the manifest right here in the template
        chart: .
        helm:
          # Pass the parameters from the YAML file into the template
          parameters:
          - name: hostname
            value: "{{hostname}}"
          - name: serviceName
            value: "{{serviceName}}"
          - name: servicePort
            value: "{{servicePort}}"
          - name: scheme
            value: "{{scheme}}"
          releaseName: "ingresstemplate"
          # Define the IngressRoute manifest as a string template
          values: |
            manifest: |
              apiVersion: traefik.containo.us/v1alpha1
              kind: IngressRoute
              metadata:
                name: '{{ .Values.serviceName }}'
              spec:
                entryPoints:
                  - websecure
                routes:
                  - match: Host(`{{ .Values.hostname }}`)
                    kind: Rule
                    services:
                      - name: '{{ .Values.serviceName }}'
                        port: {{ .Values.servicePort }}
                        {{- if .Values.scheme }}
                        scheme: {{ .Values.scheme }}
                        {{- end }}
                tls:
                  certResolver: myresolver

      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{namespace}}' # Deploy the IngressRoute into the app's namespace
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true