apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: homelab-root
  name: ingress-appset
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: ingress/*.yaml
        repoURL: https://github.com/zexianchoo/homelab-argo.git
        revision: HEAD
  template:
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: '{{serviceName}}-ingressroute'
      namespace: '{{namespace}}'
      annotations:
        argocd.argoproj.io/project: default

    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`{{hostname}}`)
          kind: Rule
          services:
            - name: '{{serviceName}}'
              # Quoting the port value makes the template more robust, as
              # IngressRoute ports can be numbers or string names.
              port: '{{servicePort}}'
              scheme: '{{scheme}}'
      tls:
        certResolver: myresolver

