apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/kyverno
      ref: values
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.4.4
      helm:
        valueFiles:
          - $values/manifests/kyverno/values.yaml      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
