apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana 
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.0.0
      helm:
        valueFiles:
          - values.yaml

  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: grafana 

  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true 