apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: apps/grafana
      ref: values
    
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.2.3
      helm:
        valueFiles:
          - $values/apps/grafana/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret-new
  namespace: grafana
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret-new
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password 