apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/grafana
      ref: values
    
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.2.3
      helm:
        valueFiles:
          - $values/manifests/grafana/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
