apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: grafana 
type: Opaque
stringData:
  admin-user: admin
  GF_SECURITY_ADMIN_PASSWORD: hihihi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret-new
  namespace: grafana
spec:
  secretStoreRef:
    name: azure-keyvault 
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret-new
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password 