admin:
  user: admin
  existingSecret: grafana-admin-secret 
  passwordKey: GF_SECURITY_ADMIN_PASSWORD

# Service configuration
service:
  type: ClusterIP 
  port: 80  

ingress:
  enabled: true
  ingressClassName: traefik 
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure 
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare

  hosts:
    - host: grafana.seanchoo.top
  path: /
  pathType: Prefix 

  tls:
    - hosts:
        - grafana.seanchoo.top 
      secretName: grafana-tls-secret 