apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  labels:
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/zexianchoo/homelab-argo.git
      targetRevision: HEAD
      path: manifests/prometheus
      ref: values
    
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.23.0
      helm:
        valueFiles:
          - $values/manifests/prometheus/values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

