apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

        - name: tailscale
          image: tailscale/tailscale:stable
          args: ["tailscaled", "--tun=userspace-networking", "--socks5-server=localhost:1055"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          volumeMounts:
            - name: tailscale-run
              mountPath: /var/run/tailscale
      volumes:
        - name: tailscale-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx 
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx
#   namespace: nginx
# spec:
#   ingressClassName: tailscale
#   defaultBackend:
#     service:
#       name: nginx
#       port:
#         number: 80
#   tls:
#     - hosts:
#       - nginx
