apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 36000 
      targetPort: 36000
  type: ClusterIP 