apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret-key
  namespace: paperless-ngx
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: paperless-secret-key
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: paperless-secret-key
        metadataPolicy: None
    - secretKey: redis-password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: paperless-redis-password
        metadataPolicy: None
