
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  pullPolicy: IfNotPresent
  tag: 2.14.7

env:
  TZ: America/Los_Angeles
  PAPERLESS_SECRET_KEY:
    valueFrom:
      secretKeyRef:
        name: paperless-secret-key   
        key: PAPERLESS_SECRET_KEY  

service:
  main:
    ports:
      http:
        port: 8000

ingress:
  main:
    enabled: true
    hosts:
      - host: paperless.seanchoo.top
        paths:
          - path: /
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    tls:
      - secretName: paperless-tls
        hosts:
          - paperless.seanchoo.top

persistence:
  data:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 300Mi
  media:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 4Gi
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi

redis:
  enabled: true
  auth:
    enabled: true
    username: ""
    existingSecret: paperless-secret-key
    existingSecretPasswordKey: paperless-postgres-password
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0



postgresql:
  enabled: true
  auth:
    database: paperless
    pexistingSecret: paperless-secret-key
    secretKeys:
      userPasswordKey: paperless-postgres-password
  primary:
    persistence:
      enabled: true
      # storageClass: ""
      size: 2Gi