apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planka-secret
  namespace: couchdb
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: planka-secret
    # creationPolicy: 'Merge'
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: planka-secret-key
        metadataPolicy: None
