apiVersion: v1
kind: Secret
metadata:
  name: planka-admin-creds
  namespace: planka
type: Opaque
stringData:
  username: admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planka-admin-creds
  namespace: planka
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: planka-admin-creds
    creationPolicy: 'Merge'
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: planka-password
        metadataPolicy: None
---
apiVersion: v1
kind: Secret
metadata:
  name: planka-oidc-creds
  namespace: planka
type: Opaque
stringData:
  clientId: 8Fx1Xc1XxcT8r62BYxo7FzGSFEpkUIPxy1CVnCWb
  clientSecret: l5MDgkE6Dhw2cIU7jQFQp0FRJwQiynhALAWtBd70hCJE17ySfyirfw9HJtbmwJQkisL8aUAycExTkU80Kh6f7J3wXZewRBJK9bzhNa9fyQnyzhaEEi87pR0dZTQc1xR7
