replicaCount: 1


# Generate a secret using openssl rand -base64 45
secretkey: TcbN4vgY95hTpQgFL2jZ8kop+zE4cpYLk3MYfBFoVOXbDxQkcfIQYytAqtRA

image:
  tag: "1.26.2"
## @param existingAdminCredsSecret Name of an existing secret containing the admin username and password
## NOTE: Must contain keys `username` and `password`
## NOTE: When it's set, the `admin_username` and `admin_password` parameters are ignored
existingAdminCredsSecret: planka-admin-creds

# Base url for PLANKA. Will override `ingress.hosts[0].host`
# Defaults to `http://localhost:3000` if ingress is disabled.
baseUrl: "planka.seanchoo.top"

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure 
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
  hosts:
    - host: planka.seanchoo.top
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: planka-tls
      hosts:
        - planka.seanchoo.top

## PVC-based data storage configuration
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 200Mi

oidc:
  enabled: true
  existingSecret: "planka-oidc-creds"
  issuerUrl: "https://authentik.seanchoo.top/application/o/planka"
  admin:
    roles: 
      - planka-admin