apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: default
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: dockerhub-creds 
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerhubcredentials }}"
  data:
  - secretKey: dockerhubcredentials
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: dockerhub-creds
      metadataPolicy: None