global:
  imagePullSecrets: 
    - name: dockerhub-creds

admissionController:
  rbac:
    viewRoleName: view
    coreClusterRole:
      extraResources:
        - apiGroups:
            - "" # For core API resources like Secrets
          resources:
            - secrets
          verbs:
            - get
            - create
            - update
            - delete
            - list
backgroundController:
  rbac:
    coreClusterRole:
      extraResources:
        - apiGroups:
            - ''
          resources:
            - secrets
          verbs:
            - get
            - create
            - update
            - delete
        - apiGroups:
            - networking.k8s.io
          resources:
            - ingresses
            - ingressclasses
            - networkpolicies
          verbs:
            - create
            - update
            - patch
            - delete
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - rolebindings
            - roles
          verbs:
            - create
            - update
            - patch
            - delete
        - apiGroups:
            - ''
          resources:
            - configmaps
            - resourcequotas
            - limitranges
          verbs:
            - create
            - update
            - patch
            - delete