apiVersion: v1
kind: Secret
metadata:
  name: couchdb-couchdb
  namespace: couchdb
type: Opaque
stringData:
  adminUsername: admin
  erlangCookie: 74a4873dc580eef6f68a3fdd4c55501e79aaf70987d34d6125d3771c683e106d
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-couchdb
  namespace: couchdb
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: couchdb-couchdb
    creationPolicy: 'Merge'
  data:
    # - secretKey: adminUsername
    #   remoteRef:
    #     conversionStrategy: Default	
    #     decodingStrategy: None
    #     key: adminUsername
    #     metadataPolicy: None
    - secretKey: adminPassword
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: couchdb-password
        metadataPolicy: None
    - secretKey: cookieAuthSecret
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: couchdb-cookie-auth 
        metadataPolicy: None

