clusterSize: 2
allowAdminParty: false
autoSetup:
  enabled: true
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: Always
  defaultDatabases:
    - _global_changes

createAdminSecret: false
adminUsername: admin

persistentVolume:
  enabled: true
  existingClaims: []
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # storageClass: "-"

enableSearch: true

ingress:
  enabled: true
  className: traefik
  hosts:
    - couch.seanchoo.top
  path: /
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure 
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
  tls:
    - secretName: couch-db-tls
      hosts:
        - couch.seanchoo.top

prometheusPort:
  enabled: true