apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  project: argocd
  source:
    path: argocd-applications
    repoURL: https://github.com/zexianchoo/homelab-argo.git
    path: apps
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true